/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CableTvRouteImport } from './routes/cable-tv'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InternetRouteImport } from './routes/internet'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as StreamingRouteImport } from './routes/streaming'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WifiRouteImport } from './routes/wifi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CableTvRoute = CableTvRouteImport.update({
  id: '/cable-tv',
  path: '/cable-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InternetRoute = InternetRouteImport.update({
  id: '/internet',
  path: '/internet',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WifiRoute = WifiRouteImport.update({
  id: '/wifi',
  path: '/wifi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cable-tv': typeof CableTvRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/internet': typeof InternetRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/streaming': typeof StreamingRoute
  '/terms': typeof TermsRoute
  '/wifi': typeof WifiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cable-tv': typeof CableTvRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/internet': typeof InternetRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/streaming': typeof StreamingRoute
  '/terms': typeof TermsRoute
  '/wifi': typeof WifiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cable-tv': typeof CableTvRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/internet': typeof InternetRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/streaming': typeof StreamingRoute
  '/terms': typeof TermsRoute
  '/wifi': typeof WifiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cable-tv'
    | '/contact'
    | '/faq'
    | '/internet'
    | '/privacy'
    | '/refund'
    | '/streaming'
    | '/terms'
    | '/wifi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cable-tv'
    | '/contact'
    | '/faq'
    | '/internet'
    | '/privacy'
    | '/refund'
    | '/streaming'
    | '/terms'
    | '/wifi'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cable-tv'
    | '/contact'
    | '/faq'
    | '/internet'
    | '/privacy'
    | '/refund'
    | '/streaming'
    | '/terms'
    | '/wifi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CableTvRoute: typeof CableTvRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InternetRoute: typeof InternetRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  StreamingRoute: typeof StreamingRoute
  TermsRoute: typeof TermsRoute
  WifiRoute: typeof WifiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cable-tv': {
      id: '/cable-tv'
      path: '/cable-tv'
      fullPath: '/cable-tv'
      preLoaderRoute: typeof CableTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internet': {
      id: '/internet'
      path: '/internet'
      fullPath: '/internet'
      preLoaderRoute: typeof InternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wifi': {
      id: '/wifi'
      path: '/wifi'
      fullPath: '/wifi'
      preLoaderRoute: typeof WifiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CableTvRoute: CableTvRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  InternetRoute: InternetRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  StreamingRoute: StreamingRoute,
  TermsRoute: TermsRoute,
  WifiRoute: WifiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
